// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function normalizeEnvValue(value?: string) {
  if (!value) return "";
  const trimmed = value.trim();
  const quoted = /^['"].*['"]$/.test(trimmed);
  return quoted ? trimmed.slice(1, -1).trim() : trimmed;
}

function isLikelyPlaceholder(value: string) {
  return /your_|example|replace|placeholder/i.test(value);
}

function isValidHttpUrl(value: string) {
  try {
    const parsed = new URL(value);
    return parsed.protocol === "https:" || parsed.protocol === "http:";
  } catch {
    return false;
  }
}

function isLikelySupabaseKey(value: string) {
  if (!value) return false;
  if (value.startsWith("sb_publishable_")) return true;
  return /^[A-Za-z0-9-_]+\.[A-Za-z0-9-_]+\.[A-Za-z0-9-_]+$/.test(value);
}

const SUPABASE_URL = normalizeEnvValue(import.meta.env.VITE_SUPABASE_URL);
const SUPABASE_PUBLISHABLE_KEY = normalizeEnvValue(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);

const hasSupabaseUrl = SUPABASE_URL.length > 0;
const hasSupabaseKey = SUPABASE_PUBLISHABLE_KEY.length > 0;

const hasValidSupabaseUrl =
  hasSupabaseUrl && isValidHttpUrl(SUPABASE_URL) && !isLikelyPlaceholder(SUPABASE_URL);
const hasValidSupabaseKey =
  hasSupabaseKey && isLikelySupabaseKey(SUPABASE_PUBLISHABLE_KEY) && !isLikelyPlaceholder(SUPABASE_PUBLISHABLE_KEY);

export const missingSupabaseEnv = [
  !hasSupabaseUrl ? "VITE_SUPABASE_URL" : null,
  !hasSupabaseKey ? "VITE_SUPABASE_PUBLISHABLE_KEY" : null,
  hasSupabaseUrl && !hasValidSupabaseUrl ? "VITE_SUPABASE_URL (valor invalido)" : null,
  hasSupabaseKey && !hasValidSupabaseKey ? "VITE_SUPABASE_PUBLISHABLE_KEY (valor invalido)" : null,
].filter((item): item is string => Boolean(item));

export const isSupabaseConfigured = missingSupabaseEnv.length === 0;

function createMissingSupabaseClient(): SupabaseClient<Database> {
  const error = new Error(`Missing Supabase environment variables: ${missingSupabaseEnv.join(", ")}`);

  return new Proxy({} as SupabaseClient<Database>, {
    get() {
      throw error;
    },
  });
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: true,
      },
    })
  : createMissingSupabaseClient();
